/* CREATE DATABASE 'SENTIMENT' */
create database sentiment;
use sentiment;

/* SELECT ALL RECORDS */
SELECT *
FROM social;

/* CHANGE COLUMN 'TIMESTAMP' TO DATETIME */
alter table social
modify column Timestamp Datetime;

/* CREATE A NEW COLUMN 'ID' */
alter table social
add column id int PRIMARY KEY auto_increment;

/* FIND USERS WITH MORE THAN 1 PLATFORMS? */

select User, 
count(Platform) as platform_count
from social
group by User
having count(Platform)>1
order by platform_count desc;

/* USERS WITH HIGHEST LIKES AND RETWEETS? */

select User,
sum(Likes) as total_likes,
sum(Retweets) as total_retweets
from social
group by User
order by total_likes desc,total_retweets Desc;
	
/* WHICH DAY OF THE MONTH SEES THE HIGHEST TOTAL RETWEETS ON AVERAGE? */

select day,
round(avg(Retweets),1) as avg_retweets
from social
group by day
order by avg_retweets desc
limit 1;


/* TOTAL LIKES FOR PAST 6  MONTHS AGO FROM THE MAX DATE */

 Select Date_sub(MAX(Timestamp), INTERVAL 6 MONTH) AS Past_6_Months_From,
Max(Timestamp) as Max_date,
sum(Likes) AS Total_Likes
from social
where Timestamp >= (select Date_sub(MAX(Timestamp), INTERVAL 6 MONTH) from social);
    
/* WHAT’S THE TOTAL LIKES GENERATED BY MONTH SINCE 6 MONTHS  TO THE MOST RECENT POST? */

select
DATE_FORMAT(Timestamp, '%Y-%m') AS Month,
SUM(Likes) AS Total_Likes
FROM social
WHERE Timestamp >= (
SELECT DATE_SUB(MAX(Timestamp), INTERVAL 6 MONTH)
FROM social
)
GROUP BY DATE_FORMAT(Timestamp, '%Y-%m')
ORDER BY Month;

/* WHICH HOUR OF THE DAY GENERATES THE HIGHEST AVERAGE LIKES ACROSS ALL PLATFORMS? */

with platform_hours as 
(
select Platform,hour ,round(avg(Likes),1) as avg_likes
from social
group by Platform,hour
order by Platform,hour,avg_likes desc
)
, 
ranks as  
(
select Platform,
hour,
avg_likes,
dense_rank()over(partition by Platform order by avg_likes desc) as rank_pos
from platform_hours
)
select * from ranks
where rank_pos <=1;

/* HOW MANY POSTS WERE MADE EACH MONTH, AND WHAT WAS THE TOTAL LIKES PER MONTH? */
select year,month,count(Text) as posts,sum(Likes) as total_likes
from social
group by year,month
order by year,month;

/* WHICH DAY OF THE MONTH SEES THE HIGHEST TOTAL RETWEETS ON AVERAGE? */

select day,round(avg(Retweets),2) as avg_retweets
from social
group by day
order by avg_retweets desc;

/* HOW DOES POSTING BEHAVIOUR DIFFER ACROSS MORNING (6–11), AFTERNOON (12–17), AND EVENING (18–23) FOR EACH PLATFORM? */

select
Platform,
CASE
WHEN Hour BETWEEN 6 AND 11 THEN 'Morning'
WHEN Hour BETWEEN 12 AND 17 THEN 'Afternoon'
WHEN Hour BETWEEN 18 AND 23 THEN 'Evening'
ELSE 'Late Night'
end as Time_of_Day,
COUNT(*) AS Post_Count,
SUM(Likes) AS Total_Likes
from social
group by Platform, Time_of_Day
order by Platform, Total_Likes DESC;

/* USERS ACTIVE ON MORE THAN ONE PLATFORM */

select a.User,
b.multiple_platform
from social as a
join 
(
select User,
count(distinct Platform) as multiple_platform 
from social 
group by User
having count(distinct Platform) >1
) as b
on a.User=b.User
group by User
order by User;

/* FOR EACH COUNTRY, WHICH PLATFORM DRIVES THE MOST TOTAL LIKES? */
select a.Country, 
a.Platform, 
a.Total_Likes
from 
(
select Country, 
Platform, 
SUM(Likes) AS Total_Likes
from social
group by Country, Platform
) as a
join 
(
select Country, MAX(Total_Likes) AS Max_Likes
from 
(
select Country, Platform, SUM(Likes) AS Total_Likes
from social
group by Country, Platform
) AS sub
group by Country
) AS b 
ON a.Country = b.Country AND a.Total_Likes = b.Max_Likes
order by a.Total_Likes desc;

/* WHICH POSTS HAVE LIKES ABOVE THEIR PLATFORM'S AVERAGE? */

select a.Text,
a.Likes,
a.platform,
b.avrg_like
from social as a
join
( 
select Platform,
round(avg(Likes),1) as avrg_like
from social
group by Platform
) as b
on a.Platform=b.Platform
where a.Likes>avrg_like
order by b.avrg_like;

/* WHAT IS THE AVERAGE LIKES AND RETWEETS FOR EACH SENTIMENT TYPE? */

select Sentiment, 
round(avg(Likes),2) av_likes, 
round(avg(Retweets),2)  av_retweets
from social
group by sentiment
order by av_likes desc;

/* WHO ARE THE TOP 3 USERS ON EACH PLATFORM BASED ON TOTAL LIKES? */

with Top_N as (select platform, user, sum(Likes) as total_likes
from social
group by platform,user)
,
Rankings as (select *,dense_rank()over(partition by platform order by total_likes desc) as rank_pos
from Top_N )
select user,platform,rank_pos
from Rankings
where rank_pos<=3;

/* CLASSIFY EACH COUNTRY AS HIGH, MEDIUM, OR LOW ENGAGEMENT BASED ON TOTAL LIKES (5000 AND ABOVE'HIGH,1000-5000 'MEDIUM, BELOW 1000 'LOW'.
WITH ENGAGEMENT */ 

select Country,sum(likes) as total_likes,case
when sum(likes)>=5000 then 'High'
when sum(likes)>=1000 then 'Medium'
else 'Low'
end as Engagement
from social
group by Country
order by total_likes desc;

/*WHAT IS THE CUMULATIVE TOTAL LIKES MONTH OVER MONTH? */

with MonthlyLikes as 
(
select Year, Month, SUM(Likes) AS Monthly_Likes
from social
group by Year, Month
)
select
Year,
Month,
Monthly_Likes,
SUM(Monthly_Likes) over (ORDER BY Year, Month) AS Running_Total
FROM MonthlyLikes
Order by Year,month;

/* WHAT IS THE TOTAL POSTS, TOTAL LIKES, TOTAL RETWEETS, AND AVERAGE LIKES PER POST FOR EACH PLATFORM? */

select Platform,
count(*) as Total_Posts,
sum(Likes) as Total_Likes,
sum(Retweets) as Total_Retweets,
round(avg(Likes), 2) as Avg_Likes_Per_Post
from social
group by Platform
order by Total_Likes desc;

/* HOW MANY POSITIVE, NEGATIVE, AND NEUTRAL POSTS DOES EACH COUNTRY HAVE? */

select Country,
sum(case when Sentiment = 'Positive' THEN 1 ELSE 0 END) AS Positive_Posts,
sum(case when Sentiment = 'Negative' THEN 1 ELSE 0 END) AS Negative_Posts,
sum(case when Sentiment = 'Neutral' THEN 1 ELSE 0 END) AS Neutral_Posts,
count(*) AS Total_Posts
from social
group by Country
order by Total_Posts desc;

/* WHICH PLATFORM HAS THE BEST RETWEET-TO-LIKES RATIO, INDICATING SHAREABILITY? */

select Platform,
SUM(Retweets) AS Total_Retweets,
SUM(Likes) AS Total_Likes,
ROUND(SUM(Retweets) * 1.0 / NULLIF(SUM(Likes), 0), 4) AS Retweet_Like_Ratio
from social
group by Platform
order by Retweet_Like_Ratio desc;




